//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuctionWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auction
    {
        public int ID { get; set; }
        public Nullable<int> IDPro { get; set; }
        public Nullable<int> IDUser { get; set; }
        public string Username { get; set; }
        public string Fullname { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public Nullable<decimal> MaxPrice { get; set; }
        public Nullable<bool> own { get; set; }
    }
}
