//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuctionWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evalution
    {
        public int ID { get; set; }
        public string IDuser { get; set; }
        public Nullable<double> Point { get; set; }
        public string Comment { get; set; }
    }
}
