//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuctionWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ID { get; set; }
        public int IDCat { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string LargeImg { get; set; }
        public string SmallImg_1 { get; set; }
        public string SmallImg_2 { get; set; }
        public string SmallImg_3 { get; set; }
        public Nullable<decimal> StartPrice { get; set; }
        public Nullable<decimal> StepPrice { get; set; }
        public Nullable<decimal> EndPrice { get; set; }
        public Nullable<decimal> IntervalTime { get; set; }
        public Nullable<bool> ExtendTime { get; set; }
        public Nullable<double> EvalutionPoint { get; set; }
        public Nullable<int> HighestKeeper { get; set; }
        public Nullable<System.DateTime> TimePost { get; set; }
        public Nullable<decimal> CurrentPrice { get; set; }
    }
}
