//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuctionWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Won
    {
        public int ID { get; set; }
        public Nullable<int> IDUser { get; set; }
        public Nullable<decimal> PriceDisplay { get; set; }
        public string Name { get; set; }
    }
}
